// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationApp.Data;

#nullable disable

namespace RegistrationApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Rivne"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Kharkiv"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Dnipro"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Warszaw"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Gdansk"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Name = "Lublin"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Name = "Poznan"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Name = "Krakow"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 3,
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 3,
                            Name = "Stuttgart"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            Name = "Cologne"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 4,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 4,
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 4,
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 4,
                            Name = "Marseille"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 4,
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Name = "Naples"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            Name = "Turin"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 5,
                            Name = "Palermo"
                        });
                });

            modelBuilder.Entity("RegistrationApp.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "France"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Italy"
                        });
                });

            modelBuilder.Entity("RegistrationApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 18,
                            CityId = 1,
                            CountryId = 1,
                            Email = "elizabeth@gmail.com",
                            Name = "Elizabeth",
                            Password = "elizabethpassword123weq",
                            PhoneNumber = "+380986815309"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            CityId = 2,
                            CountryId = 1,
                            Email = "flower@gmail.com",
                            Name = "flower",
                            Password = "flower678jhnj",
                            PhoneNumber = "+380967815495"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CityId = 3,
                            CountryId = 1,
                            Email = "grimace_shake@gmail.com",
                            Name = "grimace_shake",
                            Password = "grimaceshake89765as",
                            PhoneNumber = "+380762190863"
                        },
                        new
                        {
                            Id = 4,
                            Age = 43,
                            CityId = 4,
                            CountryId = 1,
                            Email = "jumpstyle@gmail.com",
                            Name = "jumpstyle",
                            Password = "jumpstyle009977hj",
                            PhoneNumber = "+380567812094"
                        },
                        new
                        {
                            Id = 5,
                            Age = 21,
                            CityId = 5,
                            CountryId = 1,
                            Email = "keshakaef@gmail.com",
                            Name = "keshakaef",
                            Password = "keshakaef009977hj",
                            PhoneNumber = "+380876541098"
                        },
                        new
                        {
                            Id = 6,
                            Age = 31,
                            CityId = 7,
                            CountryId = 2,
                            Email = "LiveWallpaper@gmail.com",
                            Name = "LiveWallpaper",
                            Password = "LiveWallpaperqweasd123",
                            PhoneNumber = "+480908765621"
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            CityId = 10,
                            CountryId = 2,
                            Email = "Payton@gmail.com",
                            Name = "Payton",
                            Password = "Paytonolewqwe",
                            PhoneNumber = "+480890017682"
                        },
                        new
                        {
                            Id = 8,
                            Age = 19,
                            CityId = 8,
                            CountryId = 2,
                            Email = "onepiece@gmail.com",
                            Name = "One_Piece",
                            Password = "onepiece1234fcd",
                            PhoneNumber = "+480780981123"
                        },
                        new
                        {
                            Id = 9,
                            Age = 29,
                            CityId = 6,
                            CountryId = 2,
                            Email = "isrhaul@gmail.com",
                            Name = "Isrhaul",
                            Password = "isrhaulqwefgvvv223",
                            PhoneNumber = "+480776671205"
                        },
                        new
                        {
                            Id = 10,
                            Age = 36,
                            CityId = 9,
                            CountryId = 2,
                            Email = "username_ideas@gmail.com",
                            Name = "username_ideas",
                            Password = "username_ideas567811",
                            PhoneNumber = "+480786548821"
                        },
                        new
                        {
                            Id = 11,
                            Age = 24,
                            CityId = 11,
                            CountryId = 3,
                            Email = "Yum_Yum@gmail.com",
                            Name = "Yum_Yum",
                            Password = "Yum_Yum87ygh9",
                            PhoneNumber = "+580872317850"
                        },
                        new
                        {
                            Id = 12,
                            Age = 33,
                            CityId = 12,
                            CountryId = 3,
                            Email = "tocaboca@gmail.com",
                            Name = "tocaboca",
                            Password = "tocaboca23edfgy54",
                            PhoneNumber = "+580907613411"
                        },
                        new
                        {
                            Id = 13,
                            Age = 38,
                            CityId = 13,
                            CountryId = 3,
                            Email = "roblox23@gmail.com",
                            Name = "roblox23",
                            Password = "roblox23dcaw231",
                            PhoneNumber = "+580896641289"
                        },
                        new
                        {
                            Id = 14,
                            Age = 20,
                            CityId = 14,
                            CountryId = 3,
                            Email = "efilonova@gmail.com",
                            Name = "efilonova",
                            Password = "efilonovaeqwdase23",
                            PhoneNumber = "+580987654409"
                        },
                        new
                        {
                            Id = 15,
                            Age = 28,
                            CityId = 15,
                            CountryId = 3,
                            Email = "widgetable@gmail.com",
                            Name = "widgetable",
                            Password = "widgetable312ed213edsa",
                            PhoneNumber = "+580987886520"
                        },
                        new
                        {
                            Id = 16,
                            Age = 22,
                            CityId = 16,
                            CountryId = 4,
                            Email = "queencard@gmail.com",
                            Name = "queencard",
                            Password = "queencard67uyhju182",
                            PhoneNumber = "+180128751677"
                        },
                        new
                        {
                            Id = 17,
                            Age = 26,
                            CityId = 17,
                            CountryId = 4,
                            Email = "AfterDark@gmail.com",
                            Name = "AfterDark",
                            Password = "AfterDark213edqaw32",
                            PhoneNumber = "+180886789012"
                        },
                        new
                        {
                            Id = 18,
                            Age = 31,
                            CityId = 18,
                            CountryId = 4,
                            Email = "stray_kids@gmail.com",
                            Name = "stray_kids",
                            Password = "stray_kids123edq2",
                            PhoneNumber = "+180987655567"
                        },
                        new
                        {
                            Id = 19,
                            Age = 19,
                            CityId = 19,
                            CountryId = 4,
                            Email = "DemonSlayer@gmail.com",
                            Name = "DemonSlayer",
                            Password = "DemonSlayer23edaww31",
                            PhoneNumber = "+180986782162"
                        },
                        new
                        {
                            Id = 20,
                            Age = 23,
                            CityId = 20,
                            CountryId = 4,
                            Email = "CapCut56@gmail.com",
                            Name = "CapCut56",
                            Password = "CapCut56312eqwdw",
                            PhoneNumber = "+180237872134"
                        },
                        new
                        {
                            Id = 21,
                            Age = 29,
                            CityId = 21,
                            CountryId = 5,
                            Email = "xbadmix@gmail.com",
                            Name = "xbadmix",
                            Password = "xbadmix34rfwess3",
                            PhoneNumber = "+280909876751"
                        },
                        new
                        {
                            Id = 22,
                            Age = 26,
                            CityId = 22,
                            CountryId = 5,
                            Email = "vendetta@gmail.com",
                            Name = "Vendetta",
                            Password = "vendetta213dghhht",
                            PhoneNumber = "+280118978905"
                        },
                        new
                        {
                            Id = 23,
                            Age = 21,
                            CityId = 25,
                            CountryId = 5,
                            Email = "new_jeans@gmail.com",
                            Name = "new_jeans",
                            Password = "new_jeans32eqda23",
                            PhoneNumber = "+280896547812"
                        },
                        new
                        {
                            Id = 24,
                            Age = 25,
                            CityId = 24,
                            CountryId = 5,
                            Email = "Blackpink@gmail.com",
                            Name = "Blackpink",
                            Password = "Blackpink3eqdw34123",
                            PhoneNumber = "+280897872134"
                        },
                        new
                        {
                            Id = 25,
                            Age = 23,
                            CityId = 23,
                            CountryId = 5,
                            Email = "minecraft@gmail.com",
                            Name = "minecraft",
                            Password = "minecraft23eda23",
                            PhoneNumber = "+280900761127"
                        });
                });

            modelBuilder.Entity("RegistrationApp.Models.City", b =>
                {
                    b.HasOne("RegistrationApp.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RegistrationApp.Models.User", b =>
                {
                    b.HasOne("RegistrationApp.Models.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RegistrationApp.Models.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RegistrationApp.Models.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RegistrationApp.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
